# Generated by Django 3.1 on 2021-02-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deparment',
            old_name='id',
            new_name='Departmentid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='Employeeid',
        ),
    ]
